### ISSUE TITLE
Any URL call results in a 400 Bad Request being returned

### ISSUE THREAD

**Issue by kkoppenhaver** [kkoppenhaver/wp-indesign-bridge#18]
Because of this, posts can't be populated and the plugin is basically broken.

**Comment by kkoppenhaver** [comment]
Possibly look at swapping out the HTTP library https://github.com/buraktamturk/adobe-javascript-http-client

**Comment by echodelevis** [comment]
Did you find a solution to make it work on latest wordpress... Because i try many way to do this but still say there is no WP REST API on the site. But when i typing the full url in the browser like so;

http://www.mywebsite,net/wp-json/wp/v2/posts?search= (it's worked in the browser not in Indesign)
http://www.mywebsite,net/wp-json/wp/v2/posts  (it's worked in the browser not in Indesign)

My question;  There is a way to put already the URL in the code like a var that could be more stable and more easy to make the coding of this?

I'm not a coder but something like that:
On line 119
var siteUrl.text = "http://mywebsite,com/wp-json/wp/v2/posts?search=";
On line 122
var siteUrl.text = "http://mywebsite,com/wp-json/wp/v2/posts";

and then only call it in the code with the variable?

Thanks  ;)

Screen of the data from Google browser from the site: 
![ddds](https://user-images.githubusercontent.com/25041256/39235658-8348031a-4844-11e8-8044-18db5cae40e3.png)

**Comment by kkoppenhaver** [comment]
@echodelevis Hi there, thanks for your help with debugging this. Right now, I'm looking at the options for porting this over to a proper InDesign plugin, which will require it all to be rewritten in C++.  I'll update the repository here with any more information that I find.

**Comment by kkoppenhaver** [comment]
HTTP library has been swapped out and this can continue to be written in Javascript. We will keep moving forward as-is.
